### ISSUE TITLE
Hello not really an issue but I did a thing... 

### ISSUE THREAD

**Issue by gersande** [pipcorona/HabitRPG-widget#1]
Hope this is interesting! Basically I've made your widget compatible with Wordpress, but it still has to put in manually. Will hopefully build Plugin in near future when I have more time!

http://gersande.com/display-habitrpg-as-a-user-badge-not-the-whole-rpg-on-a-wordpress-site-on-your-own-server/

**Comment by pipcorona** [comment]
That's awesome. I updated the entry on the habitrpg wiki page to have a link to it and the readme on my repository that includes a link also. Thanks!
